name: Reusable build workflow

permissions:
  packages: read

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github # value of repository/id field of the pom.xml
          server-username: GITHUB_USER_REF # env variable name for username
          server-password: GITHUB_TOKEN_REF # env variable name for GitHub Personal Access Token
      - name: Setup Settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: 'true'
      - name: Build with Maven
        run: mvn -Pgithub -B install --file pom.xml
        env:
          GITHUB_USER_REF: ${{ secrets.USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.TOKEN }}
      - run: |
          mkdir staging
          cp sms-authenticator/target/*.jar staging
          cp app-authenticator/target/*.jar staging
          cp enforce-mfa/target/*.jar staging
      - name: Create hash files
        run: |
          for jar in *.jar
          do
              sha512sum $jar | awk '{ print $1 }' > "${jar}.sha512"
          done
        working-directory: staging
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: staging
